### PR TITLE
Use Alpine linux for base

### PR DESCRIPTION
**Pull request by adamradocz**
Use the Alpine image for the ARM architecture images and for the default image. It's about half the size of the Ubuntu-based image and compiles much faster. Delete the builder image, because the built .deb artifact didn't work properly. Create Ubuntu Baseimage for the GPU and VirtualBox specific images.

### CODE REVIEW

**Comment by adamradocz** [comment]
@marius311 Do you know how to do multi tags in Docker Cloud? For consistency the `Dockerfile.baseimage-alpine` could be tagged as `latest` and `baseimage-alpine`.

**Comment by marius311** [comment]
> Do you know how to do multi tags in Docker Cloud?

**Comment by sunk818** [comment]
Alpine Linux Docker images have NULL for root password
https://news.ycombinator.com/item?id=19861725

Is this a concern for this BOINC using Alpine?

**Comment by adamradocz** [comment]
I don't think so.

**Comment by adamradocz** [comment]
In the build rule, a comma-separated list of tags does the job. I changed the build rule in the cloud.
@marius311 if you ok with the change, could you squash and merge?

**Comment by marius311** [comment]
> In the build rule, a comma-separated list of tags does the job.

**Pull request merged**
