### PR TITLE
Added support for arm32v7

### PR DESCRIPTION
**Pull request by afritzler**
Add Dockerfile to support arm32v7 devices.

### CODE REVIEW

**Comment by adamradocz** [comment]
Please change the description from ARMv8 64 to ARMv7 32

**Comment by adamradocz** [comment]
BTW what type of devices need ARMv7 support?

**Comment by afritzler** [comment]
Done!

e.g. RPi Mod 2, or in my case I running HypriotOS on a Rpi Mod 3
https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

**Comment by RichardHaselgrove** [comment]
> What type of devices need ARMv7 support?

I think @SETIguy has good knowledge of devices and their requirements.

**Comment by adamradocz** [comment]
@afritzler Could you push the ARM images to the cloud?
The format should be:
- boinc/client:arm32v7
- boinc/client:arm64v8

**Comment by afritzler** [comment]
Thx & will do!

**Pull request merged**
